### ISSUE TITLE
One-sheet for project

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/GreenEarthOS#1]
### Overview
Write a one-sheet for the Climate Collabathon project including milestones for the next 6 months.

### Action Items

- [x]  Review Civic Opportunity one-sheet
- [x]  Review another project example one-sheet
- [x]  Produce First Draft of One-Sheet
- [x]  Prepare questions for review with Bonnie
- [x] Add logo from issue #56 
- [x] Review with team
- [x] After approval
- [x] make a pdf and upload 

### Resources/Instructions

[Project One Sheet](https://docs.google.com/document/d/1mVxXVz2sTPyzJ9LjeJXq2rv2Pstc9vffh5wftIusAMo/edit)
[All Project One Sheets](https://github.com/hackforla/product-managment/issues/3)
[Civic Opportunity Project One-Sheet](https://github.com/hackforla/civic-opportunity/blob/master/Civic_Opportunity_Project_OnePage.pdf)

[directory where all one sheet pdfs get uploaded and org approval](https://github.com/hackforla/product-management/tree/master/project-one-sheets)

**Comment by sayalikotkar** [comment]
Task: Creating a concise, separate 1-sheet document based on last week's discussion

Progress: Draft ready, needs discussion with team to concretize the value proposition
Blockers: Need a better understanding of the open source civic tech projects ecosystem to figure out the value proposition of our event. i.e. how our event would be different from other climate pitch events which are targeted towards startups (eg. Innovate4Climate)
Availability: 4 hours

**Comment by sayalikotkar** [comment]
https://drive.google.com/file/d/1ZB1kjan7kMQSkoJG9tVVBuV5bjQktnCp/view?usp=sharing

**Comment by sayalikotkar** [comment]
Progress: Draft completed
Blockers: Need a better understanding of the open source civic tech projects ecosystem to figure out the value proposition of our event. i.e. how our event would be different from other climate pitch events which are targeted towards startups (eg. Innovate4Climate)
Availability: 4 hours

Next steps- Concretize value proposition & put up the 1-sheet on the HackforLA website

**Comment by sayalikotkar** [comment]
Progress: Draft ready to be put up on the HackforLA website
Blockers: Refined value proposition would be ready only after informational interviews with funders
Availability: 4 hours

Next steps- Put up the 1-sheet on the HackforLA website or wait until the refined value prop is ready

**Comment by sayalikotkar** [comment]
https://docs.google.com/document/d/1mVxXVz2sTPyzJ9LjeJXq2rv2Pstc9vffh5wftIusAMo/edit

Progress: Draft ready 
Blockers: Name & email
Availability: 2 hours
ETA: 10th Feb

**Comment by sayalikotkar** [comment]
Progress: Draft ready
Blockers: Email
Availability: 1 hour
ETA:

**Comment by PLoiya** [comment]
Logo with white background is uploaded in the onesheet.doc. Review required.

**Comment by PLoiya** [comment]
Made required changes in the onesheet document, converted to PDF and upload to the onesheet repository.

**Comment by PLoiya** [comment]
The link to the pdf onesheet  - https://github.com/hackforla/product-management/blob/master/project-one-sheets/GreenEarthOS%20one%20sheet.pdf
