### ISSUE TITLE
Branding Exercise : Tag line - Mari 

### ISSUE THREAD

**Issue by joval604** [hackforla/GreenEarthOS#103]
### Overview
We need to do branding exercise on FigJam to create a tag line for our project. 

### Action Item
- [ ] Read the examples for the tag line
- [ ] Add post on the figjam file
- [ ] Add tag lines to the post-it (Add all your tag line to one post-it)

### Resources
[FigJam File](https://www.figma.com/file/JImygEUnM6m6giaP9qg3y4/Branding-Exercise-(Copy)?node-id=0%3A1)

**Comment by ExperimentsInHonesty** [comment]
@ Mari-Garcia Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
