### ISSUE TITLE
Branding Exercise: Brand Personality - Natalia

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/GreenEarthOS#109]
### Overview
We need to do branding exercise on FigJam to create a personality for our project. 

### Action Item
- [x] Read the examples for the personality
- [x] Add post on the figjam file (images)
- [x] Add any text that explains the image to a sticky note

### Resources
[FigJam File](https://www.figma.com/file/JImygEUnM6m6giaP9qg3y4/Branding-Exercise-(Copy)?node-id=0%3A1)

#### This issue is part of this epic
#108

**Comment by Nat-nn** [comment]
[Green_Earth_Pallette.zip](https://github.com/hackforla/GreenEarthOS/files/8866130/Green_Earth_Pallette.zip)

**Comment by Nat-nn** [comment]
<img width="960" alt="1" src="https://user-images.githubusercontent.com/26047727/172747293-2a838a2b-e7c7-4a89-8854-dedc3de39c12.png">
![eva-design-color-shades 2](https://user-images.githubusercontent.com/26047727/172747298-b6f377f4-a4e0-4424-b370-fa4fdf7da413.jpg)
![eva-design-color-shades 3](https://user-images.githubusercontent.com/26047727/172747300-6b3d17e5-720f-4b2b-81f0-c33777e0424b.jpg)
![eva-design-color-shades 4](https://user-images.githubusercontent.com/26047727/172747302-644b43c9-210e-4679-83c7-b6639bf0c636.jpg)
![eva-design-color-shades 6](https://user-images.githubusercontent.com/26047727/172747304-f1ecbfad-d122-4165-b08b-de6a22a48fb4.jpg)
![eva-design-color-shades](https://user-images.githubusercontent.com/26047727/172747306-ee9ef89d-893b-4fdb-b971-3748919756e9.jpg)

**Comment by Nat-nn** [comment]
![eva-design-color-shades 2](https://user-images.githubusercontent.com/26047727/172747411-9b51fb64-eeba-451f-a03c-ea4218e422c9.jpg)

**Comment by Nat-nn** [comment]
![eva-design-color-shades 3](https://user-images.githubusercontent.com/26047727/172747427-5d6769d5-53bb-449f-8748-0ee44ba2bc18.jpg)

**Comment by Nat-nn** [comment]
![eva-design-color-shades 4](https://user-images.githubusercontent.com/26047727/172747439-3a04ec8b-8dde-4652-b0d9-bdf00c1839be.jpg)

**Comment by Nat-nn** [comment]
![eva-design-color-shades 6](https://user-images.githubusercontent.com/26047727/172747459-d973d946-238c-4cea-b9d0-91b1c643df11.jpg)

**Comment by Nat-nn** [comment]
![eva-design-color-shades](https://user-images.githubusercontent.com/26047727/172747477-6ecc0aaa-9aa2-4743-b056-ba0dfadd7857.jpg)
