### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by angle-zhang** [hackforla/GreenEarthOS#13]
### Overview
Update the readme file so it is easy for new people joining to get up to speed

### Action Items
- [x] Review the readme file and identify what information is needed and applicable (put notes in comments below)
- [x] Review the project one sheet and identify which of that information belongs in the readme.
- [x] Apply changes to readme.

### Resources/Instructions
[Climate Collabathon One Sheet]
[Climate Collabathon Repository Readme](https://github.com/hackforla/climate-collabathon/blob/main/README.md)

**Comment by sayalikotkar** [comment]
# Project title and description

The [Climate Temp Name] project seeks to create and publish a map of the current climate project support landscape including gaps. Once the landscape has been created the project will work to create visible guidance for open source projects and project ideators on how to navigate the landscape and connect with players at every appropriate stage (recruiting, mentoring, partnerships, packaging and funding) ; thereby reducing barriers to currently under represented communities.

### Project context

View the [Climate Project one-sheet](https://docs.google.com/document/d/1mVxXVz2sTPyzJ9LjeJXq2rv2Pstc9vffh5wftIusAMo/edit)


### Technology used

- [GitHub project board](https://github.com/hackforla/climate-project/projects/1)
- [Slack](https://hackforla.slack.com/archives/C01C2P7D413)
- [Google drive](https://drive.google.com/drive/u/0/folders/1N2GN3SHSXBpO_Q6dgfOp7EzbDVUz-6HO)

# How to contribute

- [Join the HackforLA slack workspace](https://hackforla.org/slack)
- Join the slack channel [#climate-collabathon](https://hackforla.slack.com/archives/C01C2P7D413) and say hi! Tell us what your skillset is and how you're looking to contribute.
- One of our product managers will add you to the meeting invite & the project resources
- Join our team meetings - Thursdays from 2 30 pm to 3 30 pm PST.

**Comment by sayalikotkar** [comment]
Progress: REadme draft created & review requested from Angela
Blocker: Need review request approved by Angela
Availability: 1 hour
ETA :

**Comment by sayalikotkar** [comment]
Progress: Done
