### ISSUE TITLE
Create a Name

### ISSUE THREAD

**Issue by angle-zhang** [hackforla/GreenEarthOS#26]
### Overview
Create a name for our project

### Action Items
- [x] Make sure domain name (.org, .com) is free
- [x] Make sure name is free on social media
- [x] Create a short write up on how the name was selected for the wiki (methodology)
### Resources/Instructions

[Video with walkthrough of process](https://www.loom.com/share/75d6144b5f1941df819f3b77161525ef)

Content posted on slack general channel on 1st feb 2021:
@channel We are still trying to find a name for a new climate project.  (our last voting was inconclusive) Please vote: https://app.usabilityhub.com/do/7f3130a93539/b79b

Taken names: 
- ClimateMatch
- ClimateConnect

**Comment by sayalikotkar** [comment]
Progress: Last survey result showed 'GreenEarthOS' to be the winner
Blocker: Team review & consensus
Availability: 1 hour
ETA:

**Comment by sayalikotkar** [comment]
Content posted on Hack for LA general channel:

@channel We need your help again :scream_cat:, picking a name for the Climate project :earth_africa:.  Thanks to everyone who has been helping :heart:   We have done 2 tests so far.
Test 1 (3 names) resulted in someone suggesting a name that we felt should be considered by all, and one that got the least amount of likes and 2 names that got an equal amount of likes
Test 2 (4 names) resulted in an even distribution of likes, however two of the names were so similar and the vote seemed to be split between them, that we think if we eliminate one, we can get a definitive answer.
Test 3 :white_check_mark: Please vote again! :white_check_mark:
app.usabilityhub.comapp.usabilityhub.com
Fast User Testing: Five Second Test, Click Test and Navigation • UsabilityHub
Capture design feedback quickly and easily with our online usability tests.

**Comment by sayalikotkar** [comment]
Name chosen: GreenEarthOS.org

**Comment by sayalikotkar** [comment]
Method of selecting a name:

The team decided to select a project name by running surveys on the Hack for LA general slack channel to determine popularity of the name options. We used [Usability Hub](https://usabilityhub.com/) to create surveys & get shareable survey links to be distributed. It took multiple iterations, the thought process for which was as follows:

Test 1: We ran a survey with 3 name options, asking participants to reorder the options in order of preference. It resulted in 2 names getting equal amount of likes & 1 getting the least amount of likes. And one of the participants suggested a new name that we felt should be included in the survey.

Test 2: We re-ran the survey with the new name option added. Itresulted in an even distribution of likes, however two of the names were so similar and the vote seemed to be split between them, which made us think if we eliminate one of them, we could get a definitive answer.

Test 3: We re-ran the survey after eliminating one amongst the two almost-identical names. The votes for the no. 1preference were almost evenly distributed again. To do a deep dive and see what most voters chose for their no. 2 option, we downloaded the excel sheet with detailed test results from Usability Hub. GreenEarthOS emerged as the most popular vote.

**Comment by sayalikotkar** [comment]
Progress: Done

**Comment by angle-zhang** [comment]
Blockers: 
- Add screenshots of different tests and walkthrough of process

**Comment by sayalikotkar** [comment]
Progress: WIP
Blockers: Need to verify whether the preference tests are a paid feature for more than 2 options
Availability: 1 hour
ETA: Team meeting on 11th March

**Comment by sayalikotkar** [comment]
Progress: Done. Created video with walkthrough of process.
Blockers: None
Availability: 1 hour
ETA - completed.
