### ISSUE TITLE
Create Project Card

### ISSUE THREAD

**Issue by angle-zhang** [hackforla/GreenEarthOS#3]
### Overview
Provide collateral for the Hack for LA website.

### Action Items

- [x] Gather Items
   - [x] 600 x 400 logo
      - [x] Alt image text
    - [x] 1500 X 700 hero image
   - [x] Name of project
   - [x] Blurb about project
   - [x] Links (github, slack channel url, Testing Site, Live Site, etc.)
   - [x] Any resources for a Getting Started link (a link to a wiki, readme(s) or both)
   - [x] leadership
      - [x] name
      - [x] role
      - [x] github handle
      - [x] slack member id 
   - [x] What you are looking for skills wise
   - [x] Status: Active
- [ ] Add project card by editing the name of the project on this issue and releasing dependency https://github.com/hackforla/website/issues/994

### Resources/Instructions
See project cards on the hackforla.org website.
~Current open issue at Hackforla website https://github.com/hackforla/website/issues/2064~

Current open issue on HfLA website https://github.com/hackforla/website/issues/2162

**Comment by angle-zhang** [comment]
leadership:
- name: Angela Zhang
- role: Product Manager
- github: angle-zhang
- slack: https://hackforla.slack.com/team/U01CDAWS3HP

**Comment by jlee2121** [comment]
leadership:

name: Jason Lee
role: Strategy & Planning
github: jlee2121
slack: https://hackforla.slack.com/team/U01HMDPDF1B

**Comment by sayalikotkar** [comment]
Leadership

name: Sayali Kotkar
role: Product Manager
github: sayalikotkar
slack: https://hackforla.slack.com/team/U01EVER7V1T

**Comment by sayalikotkar** [comment]
Readme: https://github.com/hackforla/climate-project/blob/main/README.md

**Comment by sayalikotkar** [comment]
Leadership

name: Bonnie Wolfe
role: Agile Coach
github: experiementsinhonesty
slack: https://hackforla.slack.com/team/UE1UG1YFP

**Comment by sayalikotkar** [comment]
@Safox1 @Andre310 @evonhung we need the following from you-

Name (as you want it to appear on the project team)
Role (feel free to talk to the team during our meetings if you're unsure what your title should be)

**Comment by Safox1** [comment]
Leadership

name: Serenity Fox
role: Data Scientist
github: safox1
slack: https://app.slack.com/client/U01G9FW5MGW

**Comment by Andre310** [comment]
Leadership

name: Andre Oosthuizen
role: UX Researcher
github: Andre310
slack: https://hackforla.slack.com/archives/D01K5KJHHHQ

**Comment by sayalikotkar** [comment]
Progress: All available information gathered in one place except project name & Evon's leadershp info
Blocker: project name & Evon's leadershp info
Availability: 2 hours
ETA:

**Comment by evonhung** [comment]
Leadership

Name: Evon Hung
Role: UX Researcher
Github: evonhung
Slack: https://app.slack.com/client/T04502KQX/D01B7E20MT5/user_profile/U01CDAWS3HP

**Comment by ExperimentsInHonesty** [comment]
@heyshai Please add the temp logo and hero image here
600 x 400 logo
 Alt image text
 1500 X 700 hero image
and then move this issue to the "Links/Questions/Review"

**Comment by eruan8888** [comment]
We're going to set up a usabilityhub.com test (or send a general @channel message) to ask people what they would want to see on the hero image that applies to all kinds of climate projects

**Comment by eruan8888** [comment]
@ExperimentsInHonesty  Hi all! We at GreenEarth OS want to find a header for our project page. We want something that's environment-related and applies to all kinds of climate projects. If you have any ideas, please leave them down below. Thank you!

**Comment by ExperimentsInHonesty** [comment]
@patrickm-tan please add
full name
title
github id
slack id

**Comment by patrickm-tan** [comment]
1500x700
![Green BG](https://user-images.githubusercontent.com/13408700/126582860-e1245bdc-8418-408a-b3c0-65b9e1658c3d.png)

and Logo
![GreenEarthOS Logo](https://user-images.githubusercontent.com/13408700/126582870-580eae5f-430d-4cf5-a287-e95e3ce8aa56.png)

**Comment by samaynathani** [comment]
Samay Nathani
Product Manager
@samaynathani
samay

**Comment by JessicaFB** [comment]
Name: Jessica Forrest-Baldini
Title: Data Scientist, Consultant
GitHub: @JessicaFB
Slack: @Jessica FB

**Comment by PLoiya** [comment]
full name - Puneet Loiya
title - Product Manager
github id - PLoiya
slack id - Puneet Loiya

**Comment by ExperimentsInHonesty** [comment]
Project name: GreenEarthOS

Blurb: 
The GreenEarthOS project seeks to create and publish a map of the current climate project support landscape including gaps. Once the landscape has been created the project will work to create visible guidance for open source projects and project ideators on how to navigate the landscape and connect with players at every appropriate stage (recruiting, mentoring, partnerships, packaging and funding) ; thereby reducing barriers to currently under represented communities.

Links:
GitHub: https://github.com/hackforla/climate-project
Slack: https://hackforla.slack.com/archives/C01C2P7D413

Readme: https://github.com/hackforla/climate-project/blob/main/README.md

Leadership
name: Bonnie Wolfe
role: Agile Coach
github: experiementsinhonesty
slack: https://hackforla.slack.com/team/UE1UG1YFP

Akila
Title: Product Manager
github

full name - Puneet Loiya
title - Product Manager
github id - PLoiya
slack id - U01QN0GEY6R

Samay Nathani
Product Manager
@samaynathani
U02ATEG7TFA

Name: Jessica Forrest-Baldini
Title: Data Scientist, Consultant
GitHub: @JessicaFB
Slack: U0251A1KNP4

**Comment by maria-ines-montes** [comment]
Name: María-Inés Montes
Title: UX/UI Designer
GitHub: @maria-ines-montes
Slack: U027NG94TQB

**Comment by maria-ines-montes** [comment]
Name: María-Inés Montes
Title: UX/UI Designer
GitHub: @maria-ines-montes
Slack: U027NG94TQB

**Comment by PLoiya** [comment]
Checked on the hack4la issue, status is more than 7 day without any update. automated reminder sent.

**Comment by PLoiya** [comment]
![126582870-580eae5f-430d-4cf5-a287-e95e3ce8aa56](https://user-images.githubusercontent.com/80374934/129999336-d10c8a80-77d4-4dcf-acb1-a1937d089ee1.png)

Here is the updated image 600 x 400 (3:2)  @grhhhh

**Comment by PLoiya** [comment]
Slacked Garrett on the same .. with hero image.

**Comment by ExperimentsInHonesty** [comment]
@PLoiya please re upload the pdf so that it does not have any spaces in the name https://github.com/hackforla/product-management/blob/master/project-one-sheets/GreenEarthOS%20one%20sheet.pdf needs to be like this: Civic-Tech-Structure-Product-One-Sheet.pdf

**Comment by ExperimentsInHonesty** [comment]
It turns out that I provided the wrong spelling for my github handle, and that resulted in this image showing up on our project page.  It should have been experimentsinhonesty
![greenearthos-team](https://user-images.githubusercontent.com/37763229/130367865-b4e9f9e2-c126-4b32-9e95-ae27a7d7bf87.png)

**Comment by PLoiya** [comment]
@ExperimentsInHonesty , Thanks. I uploaded the new file. One quick question - How can we delete the older version of the file from the repo ?

**Comment by ExperimentsInHonesty** [comment]
I have deleted the old pdf.

**Comment by ExperimentsInHonesty** [comment]
currently waiting on the HfLA team to finish the two updates https://github.com/hackforla/website/issues/2162
bonnie's avatar
proper link to pdf of overview

**Comment by PLoiya** [comment]
Verified/ everything is ok
