### ISSUE TITLE
Competitive Analysis for project match events

### ISSUE THREAD

**Issue by sayalikotkar** [hackforla/GreenEarthOS#39]
### Overview
Study similar events that are potential competitors to understand their merits, demerits & gaps and use that information to make recommendations yo design the Climate project.

### Action Items
- [x] List of similar events
- [x] Spreadsheet capturing key highlights & differentiators of competitor events
- [x] Recommendations for event based on competitive analysis
- [x] Meet with Raquel for data visualization
- [x] Meet with Mark for climate hackathon recommendations
### Resources/Instructions

[[Climate] Competitive Analysis](https://docs.google.com/spreadsheets/d/1M_YCauZ57cCHoxYfipm8XpQYX0pMA7mFvYKFGDqbi_0/edit#gid=1285666731)

**Comment by angle-zhang** [comment]
Q: how do we do a competitive analysis if there's no event definition?

**Comment by jlee2121** [comment]
Updated competitive analysis: https://docs.google.com/spreadsheets/d/1M_YCauZ57cCHoxYfipm8XpQYX0pMA7mFvYKFGDqbi_0/edit#gid=1285666731

**Comment by sayalikotkar** [comment]
> Q: What's the difference between interview research and a competitive analysis if there's no event definition to compare other events to?

My thought is - This is meant to be a competitive analysis covering any type of event in the climate space which facilitates funding for climate tech projects or companies.
 @jlee2121 have I summarized it right?

**Comment by jlee2121** [comment]
Updated comparative analysis: https://docs.google.com/spreadsheets/d/1M_YCauZ57cCHoxYfipm8XpQYX0pMA7mFvYKFGDqbi_0/edit#gid=1285666731

**Comment by jlee2121** [comment]
Update: Met with Raquel to redesign and reorganize comparative analysis and Mark for recommendations for any climate-related or climate-specific hackathons.

**Comment by jlee2121** [comment]
Update: added several school climate hackathons

**Comment by jlee2121** [comment]
Update: added more events/hackathons and added/reorganized criteria

**Comment by jlee2121** [comment]
Update: cleaned up spreadsheet, added a legend for color-coding, found more events/hackathons

**Comment by angle-zhang** [comment]
Next steps:
- make a google form for populating the existing spreadsheet automatically
