### ISSUE TITLE
Save climate collabathon data

### ISSUE THREAD

**Issue by sayalikotkar** [hackforla/GreenEarthOS#53]
### Overview
Save all data/information/resources related to the open climate collabathon in this issue

### Action Items

- [ ] If its a standalone resource (google doc/pdf/website) add a link in the resource section below
- [ ] If its a snippet of text, paste it in a comment on this issue, with a description of where it came from & any other context

### Resources/Instructions
- [2020 collabathon google drive](https://drive.google.com/drive/u/0/folders/17fSdfDg_jCCpm4NbeCIydPaUC2hzc2gW)

- [Collabathon Lightning Talk Application form](https://docs.google.com/forms/d/e/1FAIpQLSc90hci0Ytcgnc9T7Hq_tRiMoB3ZVuUgUooSOxttznCzTqwNw/viewform) | [responses](https://docs.google.com/spreadsheets/d/1ZtKoigfn8-BJDcnyBBMmOJGO-w8dFD3oeALkWbpHYaM/edit#gid=1572651622)

**Comment by sayalikotkar** [comment]
**The following content came from the old version of our wiki when this project was solely focused on the climate collabathon:**

# Project title and description

The [Open Climate Collabathon](https://www.collabathon.openclimate.earth) is a form of collabathon–an event based on a principle of radical collaboration and crowd-development. It is an open event mobilizing a global network of Universities, civic tech groups, startups and youth to crowd-develop an integrated climate accounting platform by leveraging state-of-the-art digital technologies. Climate accounting solutions are designed to help the world track and achieve the goals of the Paris climate agreement.

### Project context

Link to [Collabathon Wiki Co-organizer Dashboard](https://collabathon-docs.openclimate.earth/co-organizers/co-organizer-dashboard) or view the [Open Climate Collabathon White paper](https://drive.google.com/drive/u/0/folders/1NkHsMHB7Zzsseyk-xSeezfRQnSkPMzn8)

# How to contribute
- Join the Open Climate Collabathon Co-organizer's [discord](https://discord.com/invite/phe9eP9)

**Comment by StevenWuzz** [comment]
This has been added to the project board under the climate events
