### ISSUE TITLE
Setting up Figma 

### ISSUE THREAD

**Issue by angle-zhang** [hackforla/GreenEarthOS#55]
### Overview
Setting up figma 

### Action Items

- [x] Setup figma
- [x] Release dependency on issue #56 
- [x] Add other editors

### Resources/Instructions
[Figma setup guide](https://www.figma.com/proto/MX5lVWLMSTOCTDXRHaK4jF/Presentations?node-id=1%3A59&viewport=225%2C359%2C0.18814989924430847&scaling=contain)

[GreenEarthOS figma](https://www.figma.com/file/KQPvEByYrLdAen3288D13l/GreenEarthOS-designs?node-id=0%3A1)

**Comment by ExperimentsInHonesty** [comment]
@heyshai 
Please add the following people as editors to the figma
Angelea
Sayali
Jason
Andrew

**Comment by StevenWuzz** [comment]
@heyshai 
Please provide an update 
1 progress 
2 blockers
3 availability
4 ETA

**Comment by SLM-Dev** [comment]
@sayalikotkar Are you an editor on this Figma file?

https://www.figma.com/file/KQPvEByYrLdAen3288D13l/GreenEarthOS-designs?node-id=0%3A1

**Comment by SLM-Dev** [comment]
I message Sayalikotkar on slack regarding this issue?

**Comment by StevenWuzz** [comment]
I left a message to Sayali in the #product-management channel in Slack to ask for updates

**Comment by sayalikotkar** [comment]
@SLM-Dev @StevenWuzz I am not an editor on the Figma file. I have View-Only access! Sorry for the delay in getting back to you!

**Comment by ExperimentsInHonesty** [comment]
@olvia it looks like the empty figma for greenearthos [GreenEarthOS figma](https://www.figma.com/file/KQPvEByYrLdAen3288D13l/GreenEarthOS-designs?node-id=0%3A1) never got the treatment that othe r figmas got, there are no other editors on it. I am the owner and thats it.  Everyone else is just view only.  Let's talk about next steps.

**Comment by ExperimentsInHonesty** [comment]
I posted in admin channel about it.

**Comment by ExperimentsInHonesty** [comment]
I added it to the Governance agenda https://github.com/hackforla/governance/issues/82

**Comment by ExperimentsInHonesty** [comment]
I have setup a new figma in a team account that has 200 blank pages.  All people can be added as editors now by an existing team member.  Puneet has sent invites to @patrickm-tan @JessicaFB @maria-ines-montes @samaynathani - Please accept your invites.
