### ISSUE TITLE
Role recruitment: UX researcher

### ISSUE THREAD

**Issue by sayalikotkar** [hackforla/GreenEarthOS#60]
### Overview
We need to recruit a researcher to find organizations in the climate project space & categorize their information.

### Action Items

- [x] Review existing open roles on the UI/UX role board
- [x] Write draft of the volunteer opportunity, place it in the comments below
- [x] Review with team 
- [x] Post on UX/UX role board

### Resources/Instructions

[UI/UX role board](https://github.com/hackforla/UI-UX/projects/2)

**Comment by angle-zhang** [comment]
**Project Name**: Civic Opportunity Project

**Volunteer Opportunity**: Conduct background research, finalize user interview questions and conduct interviews with players in the climate ecosystem. 

**Duration**: Minimum (10 hours/week)

**Who to communicate your interest to**
- Slack channel link: [#greenearthos-climate](https://hackforla.slack.com/archives/C01C2P7D413)
- Slack name of person to contact in the channel: Angela Zhang

[Read more about the project](https://docs.google.com/document/d/1mVxXVz2sTPyzJ9LjeJXq2rv2Pstc9vffh5wftIusAMo/edit?usp=sharing)

**Resources**:

**Comment by angle-zhang** [comment]
Blockers: not sure what resources to add

**Comment by angle-zhang** [comment]
Follow-up with shaina about UX research
