### ISSUE TITLE
Create Project Landing Page

### ISSUE THREAD

**Issue by angle-zhang** [hackforla/GreenEarthOS#61]
### Overview
Landing page for people to learn more about the project

### Action Items
- [x] point domain at our github readme @ExperimentsInHonesty 
- [ ] list of items to put on our landing page
- [ ] designs for landing page

**Comment by sayalikotkar** [comment]
Add link to all completed & in progress artefacts: 
https://docs.google.com/spreadsheets/d/1M_YCauZ57cCHoxYfipm8XpQYX0pMA7mFvYKFGDqbi_0/edit#gid=1870592724

**Comment by StevenWuzz** [comment]
I have setup a github pages and set up a custom domain for it.

**Comment by ExperimentsInHonesty** [comment]
Alfa landing page has been completed.
