### ISSUE TITLE
Google Form for populating spreadsheet

### ISSUE THREAD

**Issue by jlee2121** [hackforla/GreenEarthOS#63]
### Overview
Create google form to populate a new sheet on the comparative analysis spreadsheet automatically for event organizers/hosts to share upcoming climate events.

### Action Items
- [ ] Google form gathering important information that can't be found on their website about their upcoming climate events (date, about, coaching/mentorship, contact info, link to event, etc.)
- [ ] look at the comparative analysis sheet and decide which criteria would not be found on the website (where it says N/A or NO INFO)

### Resources/Instructions
[[Climate] Comparative Analysis](https://docs.google.com/spreadsheets/d/1M_YCauZ57cCHoxYfipm8XpQYX0pMA7mFvYKFGDqbi_0/edit#gid=1285666731)

**Comment by jlee2121** [comment]
[Google form](https://docs.google.com/forms/d/19SoMjZXPreTWkjxGUwrMatHcW2qWIf_E6I-vAeYiB34/prefill)

**Comment by sayalikotkar** [comment]
We need to update the wording in the form. The intended audience for this form is 
1) People who know about these events
2) Organizations that have their own events

**Comment by StevenWuzz** [comment]
@patrickm-tan 
Please provide an update 
1 progress 
2 blockers
3 availability
4 ETA

**Comment by patrickm-tan** [comment]
Update Google Form to reflect questions in regards to getting the key information for an event overview

**Comment by patrickm-tan** [comment]
Won't be able to make tonight's meeting - no update, was busy last week. Will get the form ready by EoD Friday (06/18)

**Comment by patrickm-tan** [comment]
Added a couple new questions and reframed some others. Looks like the form now reflects the basic necessities from the spreadsheet, in the sense of basic event information.

**Comment by patrickm-tan** [comment]
Update the form to match project colours and banners.

Questions got reviewed and okay'd by team.

**Comment by patrickm-tan** [comment]
Waiting for Ellynna for the project banner/logo and google form colors.

**Comment by patrickm-tan** [comment]
Added new banner to google form

**Comment by ExperimentsInHonesty** [comment]
the form is accepted as is
