### ISSUE TITLE
Find a new time for team meetings

### ISSUE THREAD

**Issue by sayalikotkar** [hackforla/GreenEarthOS#64]
### Objective
We want to find a new time for team meetings that all team members can attend. 

### Action Items

- [x] Check with team if Wednesdays at 7 pm PDT works as that is one of the few slots Bonnie is available
- [x] Update meeting invite on google calendar
- [x] Update reminder notification on slack channel
- [x] Update team meeting time on requirements posted on all open roles boards
- [x] Update team meeting time on project readme

**Comment by patrickm-tan** [comment]
Wednesday is fine for me

**Comment by sayalikotkar** [comment]
New time agreed by all team members - Wednesdays from 7 pm to 8 pm Pacific Time
