### ISSUE TITLE
List of Climate Events

### ISSUE THREAD

**Issue by PLoiya** [hackforla/GreenEarthOS#65]
### Resources/Instructions
List of Projects - 

- [Climate Launchpad](https://climatelaunchpad.org/climatelaunchpad/)
- [Innovate4Climate](https://www.innovate4climate.com/pitch-hub)
- [Call for Code Global Challenge](https://callforcode.org/challenge/)
- [NgoLens Green Business Competition](https://www.ngolens.org/en/calls/green-business-competition-2020/)
- [Mozilla Festival](https://www.mozillafestival.org/en/?utm_source=sunset)
- [Global Climate Tech Pitch Competition](https://startupbasecamp.org/global-climate-tech-pitch-competition/)
- [NAM Grand Challenge on Human Health and Climate Change](https://tockify.com/climateresolve/detail/85/1614279600000)
- [St. Hack-trick's Day 2021](https://www.democracylab.org/index/?section=AboutEvent&id=sthacktricksday2021)
- [Digital Ag Hackathon](https://digitalag2020.splashthat.com/)
- [Sustainability Hackathon](https://events.cornell.edu/event/sustainability_hackathon)
- [The Climate Hackathon](https://betterworld.mit.edu/tapping-new-sources-climate-hackathon/)
- [Climathon](https://climathon.climate-kic.org/)
- [Environmental Hackathon](https://www.climateweeknyc.org/event/environmental-hackathon)
- [Climate Hackathon](https://hacktheclimate.devpost.com/)

All of the above events can be found in the following spreadsheet 
-[Climate Comparative Analysis for events](https://docs.google.com/spreadsheets/d/1M_YCauZ57cCHoxYfipm8XpQYX0pMA7mFvYKFGDqbi_0/edit#gid=1870592724)

**Comment by StevenWuzz** [comment]
There is a link to this issue in the resources column of our project board. Please add any new events to the top of this issue and to the spreadsheet even though this issue is already closed. Thank you!
