### ISSUE TITLE
Create an open role for a backend developer

### ISSUE THREAD

**Issue by samaynathani** [hackforla/GreenEarthOS#70]
### Overview
We need to recruit a backend developer temporarily to help us setup mkdocs on our repo so that we can start to push our findings quickly

### Action Items
- [x] Draft a proposed volunteer opportunity
- [x] Review with team 
- [x] Post on Engineering open roles board
   - [x] Post a message in #engineering slack channel with a link to board, stressing how small the ask is.
- [x] When post filled, move to filled column of open roles board 

### Resources
[role posting template]( https://github.com/hackforla/engineering/projects/2#card-53801731) 
[engineering open developer positions board](https://github.com/hackforla/engineering/projects/2)

**Comment by samaynathani** [comment]
**Project Name**: Green Earth OS
**Volunteer Opportunity**: 
We're looking for a backend developer to set up mkdocs for our git repository so we can generate webpages from markdown files.

**Duration**: 1-2 weeks

**Who to communicate your interest to**
- Slack channel link: #greenearthos-climate
- Contact samay, Puneet Loiya, or Jessica FB

[Read more about the project](https://github.com/hackforla/GreenEarthOS)

**Resources:**
[mkDocs link](https://www.mkdocs.org/)

**Comment by ExperimentsInHonesty** [comment]
@samaynathani I made a few edits to the posting above, please add it to the engineering open roles board.

**Comment by PLoiya** [comment]
Issue https://github.com/hackforla/engineering/projects/2#card-67023424 is moved to "Filled" column. Closing this item as we have Jason in the team to help us. :)
