### ISSUE TITLE
Branding Exercise : Tag line - Michelle

### ISSUE THREAD

**Issue by PLoiya** [hackforla/GreenEarthOS#98]
### Overview
We need to do branding exercise on FigJam to create a tag line for our project. 

### Action Item
- [ ] Read the examples for the tag line
- [ ] Add post on the figjam file
- [ ] Add tag lines to the post-it (Add all your tag line to one post-it)

### Resources
[FigJam File](https://www.figma.com/file/JImygEUnM6m6giaP9qg3y4/Branding-Exercise-(Copy)?node-id=0%3A1)

**Comment by ExperimentsInHonesty** [comment]
@miolow Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by miolow** [comment]
@ExperimentsInHonesty Hi all, sorry about going missing for the past two weeks, had some family things to deal with. My availability is back to every week, I'll be attending this week's meeting.

**Comment by ExperimentsInHonesty** [comment]
We got Michelle added to the figma team acount so that she can access the figjam file

**Comment by miolow** [comment]
I just put in my input into the Figjam file.
